service: digi-gold-api
frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  stage: dev

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - secretsmanager:GetSecretValue
          Resource:
            - arn:aws:secretsmanager:ap-south-1:053141520455:secret:digi_gold_secret_keys*

  environment:
    MONGO_URI: ${env:MONGO_URI}

functions:
  testDB:
    handler: source/handler/testHandler.testDB
    events:
      - httpApi:
          path: /test-db
          method: GET

  generateToken:
    handler: source/handler/authHandler.createToken
    events:
      - httpApi:
          path: /generatetoken
          method: GET

  addUser:
    handler: source/handler/userHander.addUser
    events:
      - httpApi:
          path: /addusers
          method: POST

  getUserByUserId:
    handler: source/handler/userHander.getUser
    events:
      - httpApi:
          path: /getusersbyuserid/{user_id}
          method: GET

  getUserByMobileNumber:
    handler: source/handler/userHander.getUser
    events:
      - httpApi:
          path: /getusersbymobilenumber/{mobile_number}
          method: GET

  updateUserByUserId:
    handler: source/handler/userHander.updateUser
    events:
      - httpApi:
          path: /updateusersbyuserid
          method: PUT

  deleteUserByUserId:
    handler: source/handler/userHander.deleteUser
    events:
      - httpApi:
          path: /deleteusersbyuserid
          method: POST

  getMetalPrice:
    handler: source/handler/priceHandler.getMetalPrice
    events:
      - httpApi:
          path: /getmetalprice
          method: GET

  addMetalPrice:
    handler: source/handler/priceHandler.addMetalPrice
    events:
      - schedule: cron(31 18 * * ? *)
      - httpApi:
          path: /addmetalprice
          method: POST

  calculatePrice:
    handler: source/handler/priceHandler.calculatePrice
    events:
      - httpApi:
          path: /calculateprice
          method: POST

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-esbuild

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude:
      - aws-sdk
